const CORS_PROXY = 'https://corsproxy.io/?';

export const API_INFO_BASE_URL = `${CORS_PROXY}https://api.data.gov.hk/v1/carpark-info-vacancy?data=info`;
export const API_VACANCY_BASE_URL = `${CORS_PROXY}https://api.data.gov.hk/v1/carpark-info-vacancy?data=vacancy`;
export const API_ATTRACTIONS_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/afcd_rcd_1728896853370_57183/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=Attractions_in_Country_Parks&outputFormat=geojson`;
export const API_VIEWING_POINTS_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/afcd_rcd_1635142967951_6079/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=Viewing_Point&outputFormat=geojson&maxFeatures=100`;
export const API_EV_CHARGERS_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/epd_rcd_1631080339740_69941/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=geotagging&outputFormat=geojson`;
export const API_PARKING_METERS_BASE_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/td_rcd_1638930345315_81787/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=parkingspaces&outputFormat=geojson&srsName=EPSG:4326`;
export const API_PARKING_METERS_STATUS_URL = `${CORS_PROXY}https://resource.data.one.gov.hk/td/psiparkingspaces/occupancystatus/occupancystatus.csv`;
export const API_TURN_RESTRICTIONS_URL = `${CORS_PROXY}https://static.data.gov.hk/td/road-network-v2/TURN.kmz`;
const TD_SERVICE_HASH = 'td_rcd_1731637713488_68910';
export const API_TRAFFIC_FEATURES_BASE_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/${TD_SERVICE_HASH}/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=TRAFFIC_FEATURES&outputFormat=geojson&maxFeatures=1000&srsName=EPSG:4326`;
export const API_PERMIT_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/${TD_SERVICE_HASH}/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=PERMIT&outputFormat=geojson`;
export const API_PROHIBITION_PC_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/${TD_SERVICE_HASH}/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=PROHIBITION&outputFormat=geojson&filter=<Filter><PropertyIsEqualTo><PropertyName>EXC_VEH_TYPE</PropertyName><Literal>'PC'</Literal></PropertyIsEqualTo></Filter>`;
export const API_PROHIBITION_ALL_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/${TD_SERVICE_HASH}/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=PROHIBITION&outputFormat=geojson&filter=<Filter><PropertyIsEqualTo><PropertyName>EXC_VEH_TYPE</PropertyName><Literal>'ALL'</Literal></PropertyIsEqualTo></Filter>`;
export const API_ROAD_NETWORK_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/${TD_SERVICE_HASH}/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=CENTERLINE&outputFormat=geojson`;
export const API_TRAFFIC_SPEED_URL = `${CORS_PROXY}https://resource.data.one.gov.hk/td/traffic-detectors/irnAvgSpeed-all.xml`;
export const API_OIL_STATIONS_URL = `${CORS_PROXY}https://hufung.github.io/data/stations.csv`;
export const API_OIL_PRICES_URL = `${CORS_PROXY}https://www.consumer.org.hk/pricewatch/oilwatch/opendata/oilprice.json`;
export const API_TOILETS_FEHD_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/fehd_rcd_1629969687926_30590/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=FEHD_FACI&outputFormat=geojson`;
export const API_TOILETS_AFCD_URL = `${CORS_PROXY}https://portal.csdi.gov.hk/server/services/common/afcd_rcd_1635136427551_29173/MapServer/WFSServer?service=wfs&request=GetFeature&typenames=Toilets&outputFormat=geojson`;

export const i18n = {
    'en_US': {
        modalTitle: 'Car Park Details',
        address: 'Address',
        parkId: 'Park ID',
        status: 'Status',
        vacancy: 'Vacancy',
        vac_car: 'Vacancy (Car)',
        vac_moto: 'Vacancy (Motorcycle)',
        vac_lgv: 'Vacancy (LGV)',
        vac_hgv: 'Vacancy (HGV)',
        vac_coach: 'Vacancy (Coach)',
        price_car: 'Hourly Price (Car)',
        heightLimit: 'Height Limit',
        remarks: 'Remarks',
        notAvailable: 'N/A',
        noVacancyData: 'No vacancy data available',
        errorTitle: 'Error',
        errorBody: 'Could not load car park data. Please try again later.',
        toggleCarParks: 'Car Parks',
        toggleAttractions: 'Park Attractions',
        toggleViewingPoints: 'Viewing Points',
        toggleEVChargers: 'EV Chargers',
        toggleParkingMeters: 'Parking Meters',
        toggleOilStations: 'Oil Stations',
        togglePermits: 'Permits',
        toggleProhibitions: 'Prohibitions',
        toggleTrafficSpeed: 'Traffic Speed',
        toggleTurnRestrictions: 'Turn Restrictions',
        toggleTrafficFeatures: 'Traffic Features',
        toggleToilets: 'Toilets',
        website: 'Website',
        countryPark: 'Country Park',
        street: 'Street',
        sectionOfStreet: 'Section',
        vehicleType: 'Vehicle Type',
        operatingPeriod: 'Operating Period',
        totalMeters: 'Total Meters',
        availableMeters: 'Available',
        occupiedMeters: 'Occupied',
        userLocationPopup: 'You are within {accuracy} meters of this point.',
        navigate: 'Navigate',
        stopNavigation: 'Stop Navigation',
        navigationError: 'Could not calculate route.',
        locationError: 'Could not find your location.',
        zebraCrossing: 'Zebra Crossing Ahead',
        yellowBox: 'Yellow Box Junction Ahead',
        tollPlaza: 'Toll Plaza Ahead',
        culDeSac: 'Cul-de-sac (No Through Road) Ahead',
        turnRestrictionWarning: 'Warning: Turn restriction ahead',
        arrived: 'You have arrived at your destination.',
        legendTitle: 'Legend',
        legendCarPark: 'Car Park',
        legendAttraction: 'Park Attraction',
        legendViewingPoint: 'Viewing Point',
        legendEVCharger: 'EV Charger',
        legendParkingMeter: 'Parking Meter',
        legendOilStation: 'Oil Station',
        legendTurnRestriction: 'Turn Restriction',
        legendZebraCrossing: 'Zebra Crossing',
        legendYellowBox: 'Yellow Box',
        legendTollPlaza: 'Toll Plaza',
        legendCulDeSac: 'Cul-de-sac',
        legendPermit: 'Permit',
        legendProhibition: 'Prohibition Zone',
        legendToilet: 'Toilet',
        legendTrafficSmooth: 'Smooth Traffic',
        legendTrafficSlow: 'Slow Traffic',
        legendTrafficCongested: 'Congested Traffic',
        charger_types: 'Charger Types',
        diesel: 'Diesel',
        super: 'Super',
        premium: 'Premium',
        lpg: 'LPG',
        fuelsAvailable: 'Fuels Available',
        fuelPricesTitle: 'Fuel Prices',
        company: 'Company',
        vehicle_A: 'Any Vehicles (other than Medium and Heavy Goods Vehicles, Buses, Motor Cycles and Pedal Cycles)',
        vehicle_C: 'Coaches',
        vehicle_G: 'Goods Vehicles',
        op_F: '08.00 am - 09.00 pm daily',
        op_N: '07.00 pm - Midnight daily',
        op_P: '08.00 am - 08.00 pm daily on Mondays to Saturdays (no parking on Sundays)',
        op_D: '08.00 am - Midnight on Mondays to Saturdays; 10.00 am - 10.00 pm on Sundays and public holidays',
        op_S: 'No parking on 08.00 am - 05.00 pm daily on Mondays to Fridays; 05.00 pm - Midnight daily on Mondays to Fridays; 08.00 am - Midnight daily on Saturdays; 10.00 am - 10.00 pm daily on Sundays and public holidays',
        op_H: '08:00 am - 08:00 pm daily',
        op_E: '07:00 am - 08:00 pm daily',
        op_Q: '08:00 am - 08:00 pm daily on Mondays to Saturdays; 10:00 am - 10:00 pm daily on Sundays and public holidays',
        op_J: '08:00 am - Midnight daily',
        op_A: '08:00 am - Midnight on Mondays to Saturdays (except Sundays and public holidays)',
        op_B: '08:00 am - 08:00 pm daily on Mondays to Saturdays (except Sundays and public holidays)',
        unknown: 'Unknown',
        avgSpeed: 'Avg Speed',
        routeId: 'Route ID',
        initialLoadMessage: 'First time loading may take a moment, please wait...',
        searchPlaceholder: 'Search car parks by name/address...',
        noResults: 'No car parks found matching your search.',
    },
    'zh_TW': {
        modalTitle: '停車場詳情',
        address: '地址',
        parkId: '停車場ID',
        status: '狀態',
        vacancy: '空位',
        vac_car: '空位 (私家車)',
        vac_moto: '空位 (電單車)',
        vac_lgv: '空位 (輕型貨車)',
        vac_hgv: '空位 (重型貨車)',
        vac_coach: '空位 (巴士)',
        price_car: '每小時收費 (私家車)',
        heightLimit: '高度限制',
        remarks: '備註',
        notAvailable: '沒有資料',
        noVacancyData: '沒有空位資料',
        errorTitle: '錯誤',
        errorBody: '無法加載停車場資料，請稍後再試。',
        toggleCarParks: '停車場',
        toggleAttractions: '郊野公園景點',
        toggleViewingPoints: '觀景台',
        toggleEVChargers: '電動車充電站',
        toggleParkingMeters: '咪錶泊車位',
        toggleOilStations: '油站',
        togglePermits: '許可證',
        toggleProhibitions: '禁區',
        toggleTrafficSpeed: '交通速度',
        toggleTurnRestrictions: '轉向限制',
        toggleTrafficFeatures: '交通設施',
        toggleToilets: '洗手間',
        website: '網站',
        countryPark: '郊野公園',
        street: '街道',
        sectionOfStreet: '路段',
        vehicleType: '車輛類別',
        operatingPeriod: '運作時段',
        totalMeters: '總車位數',
        availableMeters: '空置',
        occupiedMeters: '已佔用',
        userLocationPopup: '您在此地點 {accuracy} 米範圍內。',
        navigate: '導航',
        stopNavigation: '停止導航',
        navigationError: '無法計算路線。',
        locationError: '無法找到您的位置。',
        zebraCrossing: '前方斑馬線',
        yellowBox: '前方黃色方格路口',
        tollPlaza: '前方收費廣場',
        culDeSac: '前方盡頭路',
        turnRestrictionWarning: '警告：前方有轉向限制',
        arrived: '您已到達目的地。',
        legendTitle: '圖例',
        legendCarPark: '停車場',
        legendAttraction: '郊野公園景點',
        legendViewingPoint: '觀景台',
        legendEVCharger: '電動車充電站',
        legendParkingMeter: '咪錶泊車位',
        legendOilStation: '油站',
        legendTurnRestriction: '轉向限制',
        legendZebraCrossing: '斑馬線',
        legendYellowBox: '黃色方格路口',
        legendTollPlaza: '收費廣場',
        legendCulDeSac: '盡頭路',
        legendPermit: '許可證',
        legendProhibition: '禁區',
        legendToilet: '洗手間',
        legendTrafficSmooth: '交通暢順',
        legendTrafficSlow: '交通緩慢',
        legendTrafficCongested: '交通擠塞',
        charger_types: '充電器類型',
        diesel: '柴油',
        super: '超級汽油',
        premium: '特級汽油',
        lpg: '石油氣',
        fuelsAvailable: '提供燃料',
        fuelPricesTitle: '燃油價格',
        company: '公司',
        vehicle_A: '任何車輛 (中型及重型貨車、巴士、電單車及機動三輪車除外)',
        vehicle_C: '長途汽車',
        vehicle_G: '貨車',
        op_F: '每天上午 8 點至晚上 9 點',
        op_N: '每天 07:00 - 午夜',
        op_P: '週一至週六每天上午 8:00 至晚上 8:00（週日禁止停車）',
        op_D: '週一至週六上午 08:00 至午夜； 週日和公眾假期上午 10 點至晚上 10 點',
        op_S: '週一至週五每天上午 8 點至下午 5 點禁止停車； 下午 05:00 - 週一至週五每天午夜； 週六每天上午 8 點至午夜； 週日和公眾假期每天上午 10 點至晚上 10 點',
        op_H: '每天上午8時至晚上8時',
        op_E: '每天上午7時至晚上8時',
        op_Q: '逢星期一至六上午8時至晚上8時；星期日及公眾假期上午10時至晚上10時',
        op_J: '每天上午8時至午夜',
        op_A: '逢星期一至六上午8時至午夜 (星期日及公眾假期除外)',
        op_B: '逢星期一至六上午8時至晚上8時 (星期日及公眾假期除外)',
        unknown: '不詳',
        avgSpeed: '平均速度',
        routeId: '路線ID',
        initialLoadMessage: '首次加載可能需要一些時間，請稍候...',
        searchPlaceholder: '按名稱/地址搜尋停車場...',
        noResults: '找不到符合您搜尋的停車場。',
    },
    'zh_CN': {
        modalTitle: '停车场详情',
        address: '地址',
        parkId: '停车场ID',
        status: '状态',
        vacancy: '空位',
        vac_car: '空位 (私家车)',
        vac_moto: '空位 (摩托车)',
        vac_lgv: '空位 (轻型货车)',
        vac_hgv: '空位 (重型货车)',
        vac_coach: '空位 (巴士)',
        price_car: '每小时收费 (私家车)',
        heightLimit: '高度限制',
        remarks: '备注',
        notAvailable: '没有资料',
        noVacancyData: '没有空位资料',
        errorTitle: '错误',
        errorBody: '无法加载停车场资料，请稍后再试。',
        toggleCarParks: '停车场',
        toggleAttractions: '郊野公园景点',
        toggleViewingPoints: '观景台',
        toggleEVChargers: '电动车充电站',
        toggleParkingMeters: '咪表泊车位',
        toggleOilStations: '油站',
        togglePermits: '许可证',
        toggleProhibitions: '禁区',
        toggleTrafficSpeed: '交通速度',
        toggleTurnRestrictions: '转向限制',
        toggleTrafficFeatures: '交通设施',
        toggleToilets: '洗手间',
        website: '网站',
        countryPark: '郊野公园',
        street: '街道',
        sectionOfStreet: '路段',
        vehicleType: '车辆类别',
        operatingPeriod: '运作时段',
        totalMeters: '总车位数',
        availableMeters: '空置',
        occupiedMeters: '已占用',
        userLocationPopup: '您在此地点 {accuracy} 米范围内。',
        navigate: '导航',
        stopNavigation: '停止导航',
        navigationError: '无法计算路线。',
        locationError: '无法找到您的位置。',
        zebraCrossing: '前方斑马线',
        yellowBox: '前方黄色方格路口',
        tollPlaza: '前方收费广场',
        culDeSac: '前方尽头路',
        turnRestrictionWarning: '警告：前方有转向限制',
        arrived: '您已到达目的地。',
        legendTitle: '图例',
        legendCarPark: '停车场',
        legendAttraction: '郊野公园景点',
        legendViewingPoint: '观景台',
        legendEVCharger: '电动车充电站',
        legendParkingMeter: '咪表泊车位',
        legendOilStation: '油站',
        legendTurnRestriction: '转向限制',
        legendZebraCrossing: '斑马线',
        legendYellowBox: '黄色方格路口',
        legendTollPlaza: '收费广场',
        legendCulDeSac: '尽头路',
        legendPermit: '许可证',
        legendProhibition: '禁区',
        legendToilet: '洗手间',
        legendTrafficSmooth: '交通畅顺',
        legendTrafficSlow: '交通缓慢',
        legendTrafficCongested: '交通挤塞',
        charger_types: '充电器类型',
        diesel: '柴油',
        super: '超级汽油',
        premium: '特级汽油',
        lpg: '石油气',
        fuelsAvailable: '提供燃料',
        fuelPricesTitle: '燃油价格',
        company: '公司',
        vehicle_A: '任何车辆 (中型及重型货车、巴士、摩托车及机动三轮车除外)',
        vehicle_C: '长途汽车',
        vehicle_G: '货车',
        op_F: '每天上午 8 点至晚上 9 点',
        op_N: '每天 07:00 - 午夜',
        op_P: '周一至周六每天上午 8:00 至晚上 8:00（周日禁止停车）',
        op_D: '周一至周六上午 08:00 至午夜； 周日和公众假期上午 10 点至晚上 10 点',
        op_S: '周一至周五每天上午 8 点至下午 5 点禁止停车； 下午 05:00 - 周一至周五每天午夜； 周六每天上午 8 点至午夜； 周日和公众假期每天上午 10 点至晚上 10 点',
        op_H: '每天上午8时至晚上8时',
        op_E: '每天上午7时至晚上8时',
        op_Q: '逢星期一至六上午8时至晚上8时；星期日及公眾假期上午10时至晚上10时',
        op_J: '每天上午8时至午夜',
        op_A: '逢星期一至六上午8时至午夜 (星期日及公众假期除外)',
        op_B: '逢星期一至六上午8时至晚上8时 (星期日及公众假期除外)',
        unknown: '不详',
        avgSpeed: '平均速度',
        routeId: '路线ID',
        initialLoadMessage: '首次加载可能需要一些时间，请稍候...',
        searchPlaceholder: '按名称/地址搜索停车场...',
        noResults: '找不到符合您搜索的停车场。',
    },
};